### ISSUE TITLE
Cannot synthesise

### ISSUE THREAD

**Issue by rotty-dev** [BenAAndrew/Voice-API#1]
Hi, I've tried to deploy this on my own Heroku app and successfully got it to run and it shows the correct list of voices I've applied When I try to synthesise text I get a 500 Internal Server Error, I've used `heroku logs --tail` to find the full traceback and I got this

https://pastebin.com/NjVTsmTk

I'm unsure what the problem is, Using your example site returns the same 500 error as well

![image](https://user-images.githubusercontent.com/38592351/185235522-b1eb6db1-7071-4308-998e-90a6905b79fc.png)

**Comment by rotty-dev** [comment]
Update, I have found out that google drive does not download the model correctly and instead sends an html error file as a .pt file because the file size is over 100 MBs. I've manually put the model in the data folder and the error is gone but a new error has occurred when trying to make a get request. I am no longer doing this on Heroku and I'm doing this on my own docker environment.

Here's the new traceback

192.168.86.32 - - [18/Aug/2022 19:21:11] "GET /?name=David%20Attenborough&text=Some%20sample%20text HTTP/1.1" 500 -
[2022-08-18 19:21:20,775] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/container/.local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/container/.local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/container/.local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  **File "/home/container/views.py", line 83, in index
    return send_file(io.BytesIO(f.read()), attachment_filename=audio_path, mimetype="audio/wav")
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'**

**Comment by rotty-dev** [comment]
Fixed by upgrading to Flask==2.1.0
